# Generated by Django 3.0.6 on 2020-05-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0002_lesson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('lessons', models.ManyToManyField(null=True, to='lesson.Lesson')),
            ],
        ),
    ]
