# Generated by Django 3.0.6 on 2020-05-18 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_solution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 15, 30, 39, 782861, tzinfo=utc)),
        ),
    ]
