# Generated by Django 3.0.6 on 2020-05-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_auto_20200518_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='isTrue',
            field=models.BooleanField(default=False),
        ),
    ]
