# Generated by Django 3.0.6 on 2020-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_auto_20200518_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='isTrue',
            field=models.CharField(choices=[('RIGHT', 'Right'), ('FALSE', 'False'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=255),
        ),
    ]
