# Generated by Django 3.0.6 on 2020-05-19 18:44

from django.db import migrations, models
import solution.models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0006_auto_20200519_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=solution.models.upload_img_file),
        ),
    ]
