# Generated by Django 3.0.6 on 2020-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_solution_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(default=None, null=True),
        ),
    ]
