# Generated by Django 3.0.6 on 2020-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0008_auto_20200519_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='isTrue',
            field=models.CharField(choices=[('True', 'Right'), ('False', 'False'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=255),
        ),
    ]
