# Generated by Django 3.0.6 on 2020-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.SlugField()),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('thema', models.TextField()),
            ],
        ),
    ]
