# Generated by Django 3.0.6 on 2020-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('complexity', models.CharField(choices=[('LIGHT', 'Light'), ('MIDDLE', 'Middle'), ('HARD', 'Hard')], default='MIDDLE', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='task1',
            name='part',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], default='1', max_length=255),
        ),
    ]
