# Generated by Django 3.0.6 on 2020-05-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200519_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task1',
            name='thema',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.Thema'),
        ),
    ]
