# Generated by Django 3.0.6 on 2020-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_auto_20200519_1903'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('posts', models.ManyToManyField(null=True, to='post.Post')),
                ('task', models.ManyToManyField(null=True, to='task.Task1')),
                ('thema', models.ManyToManyField(null=True, to='task.Thema')),
            ],
        ),
    ]
