# Generated by Django 3.0.6 on 2020-05-16 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('947af6a0-2495-47cc-a49e-11210f960bab')),
        ),
    ]
