# Generated by Django 3.0.6 on 2020-05-16 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200516_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('fb830259-a050-480f-a081-6a472e9b1ecf')),
        ),
    ]
