# Generated by Django 3.0.6 on 2020-05-16 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200516_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('2a1c5167-6155-48a1-be0c-52e057863f89')),
        ),
    ]
