# Generated by Django 3.0.6 on 2020-05-16 12:12

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200516_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=user.models.upload_img_file),
        ),
    ]
