# Generated by Django 3.0.6 on 2020-05-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
